[2022-11-01 06:41:21,636] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: user_processing.process_user 2022-10-31T00:00:00+00:00 [queued]>
[2022-11-01 06:41:21,674] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: user_processing.process_user 2022-10-31T00:00:00+00:00 [queued]>
[2022-11-01 06:41:21,674] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-11-01 06:41:21,674] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2022-11-01 06:41:21,674] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-11-01 06:41:21,685] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): process_user> on 2022-10-31T00:00:00+00:00
[2022-11-01 06:41:21,691] {standard_task_runner.py:52} INFO - Started process 158 to run task
[2022-11-01 06:41:21,696] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'process_user', '2022-10-31T00:00:00+00:00', '--job-id', '33', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp5mroe243', '--error-file', '/tmp/tmpc7r2sepb']
[2022-11-01 06:41:21,697] {standard_task_runner.py:77} INFO - Job 33: Subtask process_user
[2022-11-01 06:41:21,767] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.process_user 2022-10-31T00:00:00+00:00 [running]> on host 8311e947f87b
[2022-11-01 06:41:21,838] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=process_user
AIRFLOW_CTX_EXECUTION_DATE=2022-10-31T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-31T00:00:00+00:00
[2022-11-01 06:41:21,846] {taskinstance.py:1455} ERROR - 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/user_processing.py", line 14, in _process_user
    user = user['results'][0]
TypeError: 'NoneType' object is not subscriptable
[2022-11-01 06:41:21,851] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=user_processing, task_id=process_user, execution_date=20221031T000000, start_date=20221101T064121, end_date=20221101T064121
[2022-11-01 06:41:21,946] {local_task_job.py:146} INFO - Task exited with return code 1
